#! /bin/bash

while ! test -f "${KEY_PATH}" || ! test -f "${CRT_PATH}"; do
	if [ $i -ge 120 ]; then
		printf "Could not setup FTPS correctly!\n"
		exit 1
	fi
	printf "Waiting for SSL certificate to be generated by nginx container... ($i/120 sec)\n"
	i=$(($i+1))
	sleep 1
done

make_user()
{
	{ echo "$FTP_PASSWORD"; echo "$FTP_PASSWORD"; } | adduser $FTP_USER
}

add_ftpuser()
{
	if [[ $(grep "jaekpark" /etc/ftpusers | wc -l) -eq 0 ]]; then
		echo "jaekpark" | tee -a /etc/ftpusers
	fi
}

make_user
mkdir -p /home/jaekpark
chmod 755 /home/jaekpark
mkdir -p /var/run/vsftpd/empty
chown -R jaekpark:jaekpark /home/jaekpark
sleep 1
vsftpd /etc/vsftpd.conf
