#! /bin/sh

cat << EOF > setup.sql
# Select mysql database
USE mysql;
FLUSH PRIVILEGES;

# create database for wp service.
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;

CREATE USER IF NOT EXISTS '$MYSQL_ADMIN'@'%' IDENTIFIED BY '$MYSQL_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_ADMIN'@'%';

# Apply Changes
FLUSH PRIVILEGES;
EOF
