#! /bin/bash

i=1
while ! test -f "${KEY_PATH}" || ! test -f "${CRT_PATH}"; do
	if [ $i -ge 120 ]; then
		printf "Could not setup TLS for adminer!\n"
		exit 1
	fi
	printf "Waiting for SSL certificate to be generated by nginx container... ($i/120 sec)\n"
	i=$(($i+1))
	sleep 1
done

echo -e "[+] Running php-fpm daemon for adminer..."
service php7.3-fpm start

echo -e "[+] Running nginx for adminer..."
nginx -g "daemon off;"
